added ci
kami-blue/bot-kt pull request #38
Opened 2020-09-28 03:22 UTC by sourTaste000

kek

2020-09-28 03:25 UTC, l1ving requested changes
Wrapper jar does not need to be included

2020-09-28 03:25 UTC, l1ving commented on README.md
> +[![CodeFactor](https://www.codefactor.io/repository/github/kami-blue/bot-kt/badge)](https://www.codefactor.io/repository/github/kami-blue/bot-kt)
Put these before donate. Also all the badges should use the same style

2020-09-28 03:31 UTC, sourTaste000 commented
wrapper jar has to be included or it will give this error:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

2020-09-28 03:34 UTC, l1ving commented
Stupid travis. It's supposed to download the jar with the wrapper

2020-09-28 03:34 UTC, sourTaste000 commented
😂

2020-09-28 03:40 UTC, wnuke commented
#36 Adds CI already, so this is probably not needed.

2020-09-28 03:41 UTC, sourTaste000 commented
i added travis

2020-09-28 03:43 UTC, wnuke commented
That's what I mean, #36 adds a workflow for GitHub's built-in CI, it also publishes Docker containers for downloading. GitHub actions is exactly like Travis, except it's built-in to GitHub.

2020-09-28 03:51 UTC, sourTaste000 commented
why u bulli me

2020-10-16 00:38 UTC, l1ving requested changes
Please update this branch to latest master. I'll do it tomorrow morning if you haven't done it.

2020-10-16 04:38 UTC, sourTaste000 commented
my brain is too small to figure out how to fix this conflict XD
if you could do it, that would be great!
thanks

2020-10-16 18:46 UTC, l1ving approved these changes

2020-10-16 18:47 UTC, merged