Improvements to issue create command
kami-blue/bot-kt pull request #71
Opened 2020-11-11 00:38 UTC by sourTaste000

closes #70

2020-11-11 00:41 UTC, l1ving requested changes

2020-11-11 00:41 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +                            val body: String? = context arg "body"
why is this nullable?

2020-11-11 00:41 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +                            form.addReaction('❎')
isn't this supposed to be red? or is that just my phone

2020-11-11 00:41 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +        if (event.reaction.emoji.name == "❎") {
use an else if please

2020-11-11 00:41 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +                message = message.error("Rejected")
leave more information, such as "Rejected issue \"$title\""

2020-11-11 00:41 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +                delay(10000)
10 seconds is more than enough, do 5

2020-11-11 00:41 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> -        } catch (e: IllegalStateException) {
these were intentionally individual, but now that commands have error handling you can just remove all of these

2020-11-11 19:54 UTC, l1ving requested changes
>         if (event.reaction.emoji.name != "✅") return

As I said earlier, this should be an if else, not an if return

2020-11-11 19:54 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +                            form.addReaction('❌')
My bad, please use `❎`

https://emojipedia.org/check-mark-button/
https://emojipedia.org/cross-mark-button/

2020-11-11 19:54 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +                            val formattedIssue = "Created by: ${message.author?.name?.toHumanReadable()} `(${message.author?.id})`\n\n${body ?: "No description provided."}"
Brigadier doesn't allow body to ever be null

2020-11-11 19:54 UTC, l1ving commented on src/main/kotlin/commands/IssueCommand.kt
> +            message.delete()
you're missing a return here

2020-11-14 02:56 UTC, l1ving commented
Looks good, I'll fix a code meme myself tomorrow

2020-11-15 03:11 UTC, sourTaste000 commented
s**t wrong branch

2020-11-26 19:10 UTC, sourTaste000 commented
LOL so many conflict

2020-11-26 19:11 UTC, l1ving commented
i fix :kannagun:

2020-12-01 01:43 UTC, l1ving requested changes
Sorry, your commit history is out of alignment, I just reimplemented this myself in ca08fe13cc041c78bcde8adc4c382b861523d0a7

2020-12-01 01:44 UTC, closed without merging