[feature] Added ;backdoor
kami-blue/bot-kt pull request #86
Opened 2020-11-22 06:45 UTC by Xiaro

Funny command

2020-11-22 12:24 UTC, l1ving commented
server specific :woeis:
I'll make it into a plugin once we add support

2020-11-22 16:58 UTC, sourTaste000 commented
🚪

2020-12-01 01:44 UTC, l1ving requested changes
Server specific, will make into plugin later

2021-01-12 05:55 UTC, sourTaste000 commented
Closed due to inactivity
Feel free to reopen this

2021-01-12 05:55 UTC, closed without merging